-- AEPS §6.3 (2026-05-07) — HTLC chains for atomic multi-hop fulfillment.
--
-- A chain is an agent-orchestrated sequence of N Lightning hold-invoices,
-- all locked to the same payment_hash H = sha256(r) where r is generated by
-- the agent. The agent reveals r to the final operator only ; LN propagates
-- the preimage back through every leg, so either the entire chain settles
-- atomically or any single timeout cascades all legs back to refund.
--
-- Why this primitive matters : EVM/x402 cannot replicate this without
-- centralization. Lightning HTLCs natively support the cross-leg atomic
-- commitment via shared payment_hash. AEPS-conformant operators advertise
-- support via `multi_hop_capable: true` in their capability descriptor.
--
-- v0.1 of the schema tracks chain orchestration state. The actual Lightning
-- integration (wiring real BOLT11 hold-invoices with externally-provided
-- payment_hash) lives in MultiHopChainService and is gated behind operator
-- capability advertisement.
--
-- See spec/AEPS-whitepaper.md §6.3.

CREATE TABLE IF NOT EXISTS aeps_multihop_chains (
  chain_id TEXT PRIMARY KEY,
  agent_pubkey TEXT NOT NULL,
  -- 64-char hex SHA-256 of the agent-generated preimage. Same H is used
  -- for every leg's HTLC, which is the structural feature that makes the
  -- chain atomic.
  preimage_hash TEXT NOT NULL,
  -- 64-char hex preimage. Populated on chain.state='complete'. Before then,
  -- only the agent (or the orchestrator acting on the agent's behalf)
  -- knows it.
  preimage_revealed TEXT,
  total_amount_msat BIGINT NOT NULL,
  n_legs INTEGER NOT NULL,
  -- planning | locked | settling | complete | aborted
  state TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  -- Hard timeout for the chain. If the chain does not reach 'complete'
  -- before expires_at, the orchestrator aborts and triggers refunds.
  -- Default 600 sec ; agent can request shorter.
  expires_at INTEGER NOT NULL,
  settled_at INTEGER,
  aborted_at INTEGER,
  abort_reason TEXT
);

CREATE INDEX IF NOT EXISTS idx_aeps_multihop_chains_agent
  ON aeps_multihop_chains (agent_pubkey, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_aeps_multihop_chains_state
  ON aeps_multihop_chains (state)
  WHERE state IN ('planning', 'locked', 'settling');

CREATE TABLE IF NOT EXISTS aeps_multihop_chain_legs (
  leg_id BIGSERIAL PRIMARY KEY,
  chain_id TEXT NOT NULL REFERENCES aeps_multihop_chains(chain_id) ON DELETE CASCADE,
  -- Position in the chain (0-indexed). Legs settle in reverse order :
  -- the agent reveals r to leg N-1 first, then the LN preimage propagates
  -- back through legs N-2 ... 0.
  leg_index INTEGER NOT NULL,
  endpoint_id TEXT NOT NULL,
  operator_pubkey TEXT NOT NULL,
  amount_msat BIGINT NOT NULL,
  -- Sha256 of the canonical request body the operator received. Used to
  -- bind the leg to the agent's intent in evidence + dispute paths.
  request_body_sha256 TEXT NOT NULL,
  -- planned | locked | settled | aborted
  state TEXT NOT NULL,
  -- Opaque LN reference (BOLT11 hold-invoice payment hash, or in v0.1 a
  -- mock value produced by the orchestrator). Verifiable by anyone with
  -- LN access via `lookupinvoice` on the operator's node.
  htlc_ref TEXT,
  -- Sha256 of the operator's response body, set once the operator delivers
  -- content and before the chain settles.
  fulfilled_response_sha256 TEXT,
  locked_at INTEGER,
  fulfilled_at INTEGER,
  settled_at INTEGER,
  CONSTRAINT aeps_multihop_chain_legs_unique UNIQUE (chain_id, leg_index)
);

CREATE INDEX IF NOT EXISTS idx_aeps_multihop_chain_legs_chain
  ON aeps_multihop_chain_legs (chain_id, leg_index ASC);

COMMENT ON TABLE aeps_multihop_chains IS
  'AEPS §6.3 — agent-orchestrated multi-hop HTLC chain. All legs share one payment_hash; either all settle atomically or all refund. See spec/AEPS-whitepaper.md.';

INSERT INTO schema_version (version, applied_at, description)
VALUES (78, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
        'AEPS §6.3 — aeps_multihop_chains + legs (atomic multi-hop primitive)')
ON CONFLICT (version) DO NOTHING;
