// @satrank/sdk — Client SDK for the SatRank API
export {
  SatRankClient,
  SatRankError,
  // Typed error subclasses — agents can dispatch on type instead of string-matching
  ValidationSatRankError,
  UnauthorizedError,
  PaymentRequiredError,
  BalanceExhaustedError,
  PaymentPendingError,
  NotFoundSatRankError,
  DuplicateReportError,
  RateLimitedError,
  ServiceUnavailableError,
  TimeoutError,
  NetworkError,
} from './client';
export type { SatRankClientOptions, NostrScoreEvent, WatchlistChange, WatchlistResponse } from './client';
export type {
  AgentScoreResponse,
  TopAgentsResponse,
  SearchAgentsResponse,
  HistoryResponse,
  AttestationsResponse,
  HealthResponse,
  NetworkStats,
  VersionResponse,
  ScoreComponents,
  ScoreEvidence,
  TransactionSample,
  LightningGraphEvidence,
  ReputationEvidence,
  PopularityEvidence,
  PaginationMeta,
  ConfidenceLevel,
  AgentSource,
  AmountBucket,
  PaymentProtocol,
  // Verdict types
  VerdictResponse,
  Verdict,
  VerdictFlag,
  PersonalTrust,
  RiskProfile,
  RiskProfileName,
  RiskLevel,
  // Temporal types
  ScoreDelta,
  TrendDirection,
  AgentAlert,
  TopMover,
  NetworkTrends,
  // Attestation types
  AttestationCategory,
  CreateAttestationInput,
  CreateAttestationResponse,
  BatchVerdictItem,
  MoversResponse,
  // Decision types
  WalletProvider,
  DecideRequest,
  DecideResponse,
  ReportRequest,
  ReportResponse,
  ProfileResponse,
  BestRouteRequest,
  BestRouteResponse,
  BestRouteCandidate,
  PaymentResult,
  TransactResult,
  // Deposit types
  DepositInvoiceResponse,
  DepositVerifyResponse,
  // Service discovery types
  ServiceSearchParams,
  ServiceResult,
  ServiceCategory,
} from './types';
